stages:
- build
variables:
  VERSION: 0.1.0

build:linux:
  image: asherd/veruscoin-cross-compiler:pool
  variables:
    DOCKER_DRIVER: overlay2
  stage: build
  before_script:
  script:
  - mkdir build 
  - cd build 
  - cmake -DUSE_CUDA_DJEZO=0 -DUSE_CPU_XENONCAT=0 .. 
  - make -j $(nproc) 
  - cd cpu_xenoncat/asm_linux/
  - sh assemble.sh
  - cd ../../../
  - mkdir build && cd build
  - cmake ../nheqminer
  - make -j $(nproc)
  artifacts:
    paths: ["build"]
    expire_in: 1 week


