stages:
- build
variables:
  VERSION: 0.1.0

build:linux:
  image: asherd/veruscoin-cross-compiler:pool-linux
  variables:
    DOCKER_DRIVER: overlay2
    CXX: usr/bin/g++-8 
    CC: usr/bin/gcc-8
  stage: build
  before_script:
  script:
  - mkdir build && cd build
  - cmake -DUSE_CUDA_DJEZO=0 -DUSE_CPU_XENONCAT=0 .. 
  - make -j$(nproc) 
  artifacts:
    paths: ["build/nheqminer"]
    expire_in: 1 week


