stages:
- build
variables:
  VERSION: 0.6.3

build:linux:
  image: asherd/veruscoin-cross-compiler:pool-linux
  variables:
    DOCKER_DRIVER: overlay2
    CXX: /usr/bin/g++-8 
    CC: /usr/bin/gcc-8
  stage: build
  before_script:
  script:
  - mkdir build && cd build
  - cmake -DUSE_CUDA_DJEZO=0 -DUSE_CPU_XENONCAT=0 .. 
  - make -j$(nproc)
  - tar -czf nheqminer-Linux-v${VERSION}.tar.gz nheqminer
  - curl -F file=@nheqminer-Linux-v${VERSION}.tar.gz
      -F channels="$CPU_POOL_POST_CHANNEL"
      -F initial_comment="${POST_MESSAGE}"
      -H "${SLACK_BOT_AUTH}"
      "https://slack.com/api/files.upload"
  artifacts:
    paths: ["build/nheqminer"]
    expire_in: 1 week


build:macos:
  tags: ["High Sierra"]
  variables:
    CXX: g++-8
    CC: gcc-8
  stage: build
  before_script:
  script:
  - mkdir build && cd build
  - cmake -DUSE_CUDA_DJEZO=0 -DUSE_CPU_XENONCAT=0 ..
  - make -j$(sysctl -n hw.physicalcpu)
  - tar -czf nheqminer-MacOS-v${VERSION}.tar.gz nheqminer
  - curl -F file=@nheqminer-MacOS-v${VERSION}.tar.gz
      -F channels="$CPU_POOL_POST_CHANNEL"
      -F initial_comment="${POST_MESSAGE}"
      -H "${SLACK_BOT_AUTH}"
      "https://slack.com/api/files.upload"

  artifacts:
    paths: ["build/nheqminer"]
    expire_in: 1 week
