stages:
- build
variables:
  VERSION: 0.1.0

build:linux:
  image: asherd/veruscoin-cross-compiler:pool
  variables:
    DOCKER_DRIVER: overlay2
  stage: build
  before_script:
  script:
  - cd nheqminer/cpu_xenoncat/asm_linux/
  - sh assemble.sh
  - cd ../../../
  - mkdir build && cd build
  - cmake ../nheqminer
  - make -j $(nproc)


