stages:
- build
variables:
  VERSION: 0.1.0

build:linux:
  image: asherd/veruscoin-cross-compiler:pool
  variables:
    DOCKER_DRIVER: overlay2

  stage: build
  before_script:
  - unset CC; unset CXX
  script:
  - cmake -DUSE_CUDA_DJEZO=0 -DUSE_CPU_XENONCAT=0 .
  - make -j $(nproc) 
  artifacts:
    paths: ["build/nheqminer"]
    expire_in: 1 week


